
export const FETCH_REPOSITORY_START = 'FETCH_REPOSITORY_START'
export const FETCH_REPOSITORY_SUCCESS = 'FETCH_REPOSITORY_SUCCESS'
export const FETCH_REPOSITORY_FAIL = 'FETCH_REPOSITORY_FAIL'
export const FETCH_REPOSITORY_CLEANUP = 'FETCH_REPOSITORY_CLEANUP'


export const FETCH_ORGS_START = 'FETCH_ORGS_START'
export const FETCH_ORGS_SUCCESS = 'FETCH_ORGS_SUCCESS'
export const FETCH_ORGS_FAIL = 'FETCH_ORGS_FAIL'
export const FETCH_ORGS_CLEANUP = 'FETCH_ORGS_CLEANUP'
